import os
import shutil
import pytest


@pytest.fixture(autouse=True)
def _run_around_tests() -> None:
  """Automatically called fixture that clears output files generated by tests."""
  clear_files("tests/output")
  clear_files("tests/input")
  yield
  clear_files("tests/output")
  clear_files("tests/input")


def clear_files(path) -> None:
  """Deletes files generated by tests."""

  contents = [item for item in os.listdir(path) if item != ".gitkeep"]

  for item in contents:
    item_path = os.path.join(path, item)
    try:
      #try to remove a directory (with contents)
      shutil.rmtree(item_path)
      print(f"removed dir: {item_path}")
    except OSError:
      # or a file is not a directory
      print(f"removing file: {item_path}")
      os.remove(item_path)